# -*- coding: utf-8 -*-

from enum import Enum


class StsCodes(Enum):
    """Official doc page8-2 """

    """Local STS Error Codes"""
    SUCCESS = 0x0
    DST_OUT_OF_BUFFER = 0x01
    DELIVERY_NOT_GUARANTEED_NO_ACK = 0x02
    DUPLICATE_TOKEN_HOLDER = 0x03
    LOCAL_PORT_DISCONNECTED = 0x04
    APP_LAYER_TIMEOUT_WAITING_FOR_RESPONSE = 0x05
    DUPLICATE_NODE_DETECTED = 0x06
    STATION_OFFLINE = 0x07
    HARDWARE_FAULT = 0x08

    """Remote STS Error Codes"""
    ILLEGAL_COMMAND_OR_FORMAT = 0x10
    HOST_PROBLEM_WONT_COMMUNICATE = 0x20
    REMOTE_HOST_MISSING = 0x30
    REMOTE_HARDWARE_FAULT = 0x40
    ADDRESS_PROBLEM_OR_MEMORY_PROTECT_RUNGS = 0x50
    COMMAND_PROTECTION_SELECTION = 0x60
    PROCESSOR_IN_PROGRAM_MODE = 0x70
    COMPATIBILITY_FILE_MISSING_OR_COMM_ZONE_PROBLEM = 0x80
    CANNOT_BUFFER_COMMAND = 0x90
    WAIT_ACK_BUFFER_FULL = 0xa0
    PROBLEM_DUE_TO_DOWNLOAD = 0xb0
    WAIT_ACK_BUFFER_FULL_2 = 0xc0
    UNUSED_1 = 0xd0
    UNUSED_2 = 0xe0
    ERROR_CODE_IN_EXT_STS_BYTE = 0xf0
